-- Ensure all photos belong to the default collection and add optimized image columns
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO collections (id, name, description)
VALUES (1, 'Default Collection', 'Default photo collection for this portfolio')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE collections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read collections" ON collections;
DROP POLICY IF EXISTS "Owner can manage collections" ON collections;

CREATE POLICY "Allow public read collections" ON collections
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Owner can manage collections" ON collections
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

ALTER TABLE photos
ADD COLUMN IF NOT EXISTS collection_id BIGINT REFERENCES collections(id) DEFAULT 1;

UPDATE photos
SET collection_id = 1
WHERE collection_id IS NULL;

ALTER TABLE photos 
ADD COLUMN IF NOT EXISTS thumbnail_s3_key TEXT,
ADD COLUMN IF NOT EXISTS medium_s3_key TEXT,
ADD COLUMN IF NOT EXISTS dimensions JSONB;

-- Add helpful comment
COMMENT ON COLUMN photos.collection_id IS 'Foreign key for the collection this photo belongs to';
COMMENT ON COLUMN photos.thumbnail_s3_key IS 'S3 key for 400px thumbnail version';
COMMENT ON COLUMN photos.medium_s3_key IS 'S3 key for 1200px medium version';
COMMENT ON COLUMN photos.dimensions IS 'Original image dimensions {width, height}';
